apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/morey-tech/demo-app-test
  newTag: ec5f6981f7103f2777ccb51627560bb6a50ee69d
